##################
### deployment ###
##################
'deployment': '#!/bin/bash -e

echo "==> entering step for loading chroot at $(date)"

time_load=$(date +%s)

#FIXME HACK BEGIN

ubuntu_distro=precise

arch=amd64

ros_distro=hydro

ROS_DISTRO=hydro    

repository=fiad_scenario

#FIXME HACK END

if [ -z "$ROS_DISTRO" ]; then

    ROS_DISTRO=$ros_distro

fi

if [ -z "$ros_distro" ]; then

    ros_distro=$ROS_DISTRO

fi

new_basetgz=${ubuntu_distro}__${arch}__${ROS_DISTRO}

basetgz=@(USERNAME)__${new_basetgz}__${repository}

cat &gt; $WORKSPACE/env_vars.sh &lt;&lt;DELIM

JOBNAME=$JOB_NAME

ROSDISTRO=$ROS_DISTRO

REPOSITORY=$repository

UBUNTUDISTRO=$ubuntu_distro

ARCH=$arch

PIPELINE_REPOS_OWNER=@(PIPELINEREPOSOWNER)

JOBTYPE=@(JOB_TYPE_NAME)

export BUILD_ID=$BUILD_ID

DELIM

echo "==> entering step for proccessing inside chroot at $(date)"

time_processing=$(date +%s)

if [ $arch == "i386" ]; then

    setarch i386 sudo pbuilder execute --basetgz $WORKSPACE/chroot_tarballs/in_use/${basetgz} --bindmounts /dev $WORKSPACE -- $WORKSPACE/jenkins_setup/scripts/pbuilder_env.sh $WORKSPACE

else

    sudo pbuilder execute --basetgz $WORKSPACE/chroot_tarballs/in_use/${basetgz} --bindmounts /dev $WORKSPACE -- $WORKSPACE/jenkins_setup/scripts/pbuilder_env.sh $WORKSPACE

fi

# change file ownership to "jenkins" user (files generated out of chroot have owner "root") (TODO: maybe in post-build step to make sure that also aborted jobs have correct ownership)

sudo chown -R $(id -un):$(id -gn) $WORKSPACE

echo

echo "==> finished job at $(date)"

time_end=$(date +%s)

# duration steps: load, processing, end

echo "durations:"

echo "loading chroot in             " $(date -d @`expr $time_processing - $time_load` +%M:%S)
 
echo "processing inside chroot in   " $(date -d @`expr $time_end - $time_processing` +%M:%S)

echo "total                         " $(date -d @`expr $time_end - $time_load` +%M:%S)

echo
'
