'triggers':
  'none': '<triggers class="vector"/>'
  'periodic':
    'continuous': ' <triggers class="vector"> <hudson.triggers.TimerTrigger> <spec>*/5 * * * *</spec> </hudson.triggers.TimerTrigger> </triggers>'
    'nightly': ' <triggers class="vector"> <hudson.triggers.TimerTrigger> <spec>0 3 * * *</spec> </hudson.triggers.TimerTrigger> </triggers>'
    'daily': ' <triggers class="vector"> <hudson.triggers.TimerTrigger> <spec>0 13 * * *</spec> </hudson.triggers.TimerTrigger> </triggers>'
    'weekly': ' <triggers class="vector"> <hudson.triggers.TimerTrigger> <spec>0 2 * * 0</spec> </hudson.triggers.TimerTrigger> </triggers>'
    'monthly': ' <triggers class="vector"> <hudson.triggers.TimerTrigger> <spec>0 4 1 * *</spec> </hudson.triggers.TimerTrigger> </triggers>'
  'vcs': '<triggers class="vector"> <hudson.triggers.SCMTrigger> <spec>H/10 * * * *</spec> </hudson.triggers.SCMTrigger> </triggers>'
  'resulttrigger': '<triggers class="vector"> <org.jenkinsci.plugins.buildresulttrigger.BuildResultTrigger> <spec>* * * * *</spec> <jobsInfo> <org.jenkinsci.plugins.buildresulttrigger.model.BuildResultTriggerInfo> <jobName>@(RESULTTRIGGER)</jobName> <checkedResults> @(RESULTS) </checkedResults> </org.jenkinsci.plugins.buildresulttrigger.model.BuildResultTriggerInfo> </jobsInfo> </org.jenkinsci.plugins.buildresulttrigger.BuildResultTrigger> </triggers>'
  'resulttrigger_results': '<org.jenkinsci.plugins.buildresulttrigger.model.CheckedResult> <checked>@(RESULT_STATUS)</checked> </org.jenkinsci.plugins.buildresulttrigger.model.CheckedResult>'

'vcs':
  'none' : '<scm class="hudson.scm.NullSCM"/>'
  'svn' : '<scm class="hudson.scm.SubversionSCM"> <locations> <hudson.scm.SubversionSCM_-ModuleLocation> <remote>@(URI)</remote> <local>monitored_vcs</local> </hudson.scm.SubversionSCM_-ModuleLocation> </locations> <useUpdate>false</useUpdate> <doRevert>false</doRevert> <excludedRegions/> <includedRegions/> <excludedUsers/> <excludedRevprop/> <excludedCommitMessages/> </scm> <scmCheckoutRetryCount>3</scmCheckoutRetryCount>'
  'hg' : '<scm class="hudson.plugins.mercurial.MercurialSCM"> <source>@(URI)</source> <modules/> <subdir>monitored_vcs</subdir> <clean>false</clean> <forest>false</forest> <branch>@(BRANCH)</branch> </scm> <scmCheckoutRetryCount>3</scmCheckoutRetryCount>'
  'git': '<scm class="hudson.plugins.git.GitSCM"> <configVersion>2</configVersion> <userRemoteConfigs> <hudson.plugins.git.UserRemoteConfig> <name>origin</name> <refspec>+refs/heads/@(BRANCH):refs/remotes/origin/@(BRANCH)</refspec> <url>@(URI)</url> </hudson.plugins.git.UserRemoteConfig> </userRemoteConfigs> <branches> <hudson.plugins.git.BranchSpec> <name>@(BRANCH)</name> </hudson.plugins.git.BranchSpec> </branches> <disableSubmodules>false</disableSubmodules> <recursiveSubmodules>true</recursiveSubmodules> <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations> <authorOrCommitter>false</authorOrCommitter> <clean>false</clean> <wipeOutWorkspace>false</wipeOutWorkspace> <pruneBranches>false</pruneBranches> <remotePoll>false</remotePoll> <ignoreNotifyCommit>false</ignoreNotifyCommit> <buildChooser class="hudson.plugins.git.util.DefaultBuildChooser"/> <gitTool>Default</gitTool> <submoduleCfg class="list"/> <relativeTargetDir>monitored_vcs</relativeTargetDir> <reference/> <excludedRegions/> <excludedUsers/> <gitConfigName/> <gitConfigEmail/> <skipTag>false</skipTag> <includedRegions/> <scmName/> </scm> <scmCheckoutRetryCount>3</scmCheckoutRetryCount>'

'junit_testresults': '<hudson.tasks.junit.JUnitResultArchiver> <testResults>test_results/*.xml</testResults> <keepLongStdio>false</keepLongStdio> <testDataPublishers/> </hudson.tasks.junit.JUnitResultArchiver>'

'mailer': '<hudson.tasks.Mailer> <recipients>@(EMAIL)</recipients> <dontNotifyEveryUnstableBuild>false</dontNotifyEveryUnstableBuild> <sendToIndividuals>@(EMAIL_TO_COMMITTER)</sendToIndividuals> </hudson.tasks.Mailer>'

'emailext': '<hudson.plugins.emailext.ExtendedEmailPublisher>
      <recipientList>@(EMAIL)</recipientList>
      <configuredTriggers>
        <hudson.plugins.emailext.plugins.trigger.UnstableTrigger>
          <email>
            <recipientList></recipientList>
            <subject>$PROJECT_DEFAULT_SUBJECT</subject>
            <body>$PROJECT_DEFAULT_CONTENT</body>
            <sendToDevelopers>@(EMAIL_TO_COMMITTER)</sendToDevelopers>
            <sendToRequester>false</sendToRequester>
            <includeCulprits>false</includeCulprits>
            <sendToRecipientList>true</sendToRecipientList>
            <attachmentsPattern></attachmentsPattern>
            <attachBuildLog>false</attachBuildLog>
            <replyTo></replyTo>
          </email>
        </hudson.plugins.emailext.plugins.trigger.UnstableTrigger>
        <hudson.plugins.emailext.plugins.trigger.FailureTrigger>
          <email>
            <recipientList></recipientList>
            <subject>$PROJECT_DEFAULT_SUBJECT</subject>
            <body>$PROJECT_DEFAULT_CONTENT</body>
            <sendToDevelopers>@(EMAIL_TO_COMMITTER)</sendToDevelopers>
            <sendToRequester>false</sendToRequester>
            <includeCulprits>false</includeCulprits>
            <sendToRecipientList>true</sendToRecipientList>
            <attachmentsPattern></attachmentsPattern>
            <attachBuildLog>false</attachBuildLog>
            <replyTo></replyTo>
          </email>
        </hudson.plugins.emailext.plugins.trigger.FailureTrigger>
        <hudson.plugins.emailext.plugins.trigger.FixedTrigger>
          <email>
            <recipientList></recipientList>
            <subject>$PROJECT_DEFAULT_SUBJECT</subject>
            <body>$PROJECT_DEFAULT_CONTENT</body>
            <sendToDevelopers>@(EMAIL_TO_COMMITTER)</sendToDevelopers>
            <sendToRequester>false</sendToRequester>
            <includeCulprits>false</includeCulprits>
            <sendToRecipientList>true</sendToRecipientList>
            <attachmentsPattern></attachmentsPattern>
            <attachBuildLog>false</attachBuildLog>
            <replyTo></replyTo>
          </email>
        </hudson.plugins.emailext.plugins.trigger.FixedTrigger>
      </configuredTriggers>
      <contentType>text/html</contentType>
<defaultSubject>$BUILD_STATUS: @(JOBNAME) of ${ENV, var="repository"};  ${ENV, var="ros_distro"}, ${ENV, var="ubuntu_distro"}, ${ENV, var="arch"} - Build # $BUILD_NUMBER!</defaultSubject>
      <defaultContent>${JELLY_SCRIPT,template=&quot;html-with-health-builds-tests&quot;}</defaultContent>
      <attachmentsPattern></attachmentsPattern>
      <presendScript></presendScript>
      <attachBuildLog>true</attachBuildLog>
      <replyTo></replyTo>
      <matrixTriggerMode>ONLY_CONFIGURATIONS</matrixTriggerMode>
    </hudson.plugins.emailext.ExtendedEmailPublisher>'

'parameters':
  'block': '<hudson.model.ParametersDefinitionProperty> <parameterDefinitions> @(PARAMS) </parameterDefinitions> </hudson.model.ParametersDefinitionProperty>'
  'param': '<hudson.model.StringParameterDefinition> <name>@(PARAM)</name> <description> </description> <defaultValue> </defaultValue>  </hudson.model.StringParameterDefinition>'

'authorizationmatrix':
    'read': '<hudson.security.AuthorizationMatrixProperty> <permission>hudson.model.Item.Read:@(USERNAME)</permission> </hudson.security.AuthorizationMatrixProperty>'
    'build': '<hudson.security.AuthorizationMatrixProperty> <permission>hudson.model.Item.Build:@(USERNAME)</permission> </hudson.security.AuthorizationMatrixProperty>'

'parameterizedtrigger':
  'basic':
    '<hudson.plugins.parameterizedtrigger.BuildTrigger> <configs> @(TRIGGERS) </configs> </hudson.plugins.parameterizedtrigger.BuildTrigger>'
  'trigger':
    '<hudson.plugins.parameterizedtrigger.BuildTriggerConfig> <configs> @(CONFIGS) </configs> <projects> @(PROJECTLIST) </projects> <condition>@(CONDITION)</condition> <triggerWithNoParameters>@(NOPARAM)</triggerWithNoParameters> </hudson.plugins.parameterizedtrigger.BuildTriggerConfig>'
  'matrix_subset':
    '<hudson.plugins.parameterizedtrigger.matrix.MatrixSubsetBuildParameters> <filter>@(FILTER)</filter> </hudson.plugins.parameterizedtrigger.matrix.MatrixSubsetBuildParameters>'
  'predef_param':
    '<hudson.plugins.parameterizedtrigger.PredefinedBuildParameters> <properties>@(PARAMETER)</properties> </hudson.plugins.parameterizedtrigger.PredefinedBuildParameters>'

'matrix':
  'basic': '<axes> @(AXES) <hudson.matrix.LabelAxis> <name>label</name> <values> <string>@(NODE)</string> </values> </hudson.matrix.LabelAxis> </axes> <executionStrategy class="hudson.matrix.DefaultMatrixExecutionStrategyImpl"> <runSequentially>false</runSequentially> </executionStrategy>'
  'axis': '<hudson.matrix.TextAxis> <name>@(NAME)</name> <values> @(VALUES) </values> </hudson.matrix.TextAxis>'
  'value': '<string>@(VALUE)</string>'
  'filter': '<combinationFilter>@(FILTER)</combinationFilter>'

'jointrigger': '<join.JoinTrigger> <joinProjects>@(JOIN_PROJECTS)</joinProjects> <joinPublishers> @(PARAMETERIZED_TRIGGER) </joinPublishers> <evenIfDownstreamUnstable>@(JOIN_UNSTABLE)</evenIfDownstreamUnstable> </join.JoinTrigger>'

'groovypostbuild':
    'basic': "<org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder> <groovyScript>@(GROOVYPB_SCRIPT)</groovyScript> <behavior>@(GROOVYPB_BEHAVIOR)</behavior> </org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder>"
    'script':
        'enable': "if(manager.build.result.isBetterOrEqualTo(hudson.model.Result.FAILURE)) {\n manager.listener.logger.println('Because this build did not fail:')\n for (project in @(PROJECT_LIST)) {\n  manager.listener.logger.println(' - ' + project)\n  manager.hudson.getItem(project).enable()\n }\n manager.listener.logger.println('will be enabled.')\n}"
        'join_enable': ""
        'disable': "for (project in @(PROJECT_LIST)) {\n manager.listener.logger.println('Disable ' + project + ' job')\n manager.hudson.getItem(project).disable()\n}"

'postbuildtrigger': '<hudson.tasks.BuildTrigger> <childProjects>@(CHILD_PROJECTS)</childProjects> <threshold> <name>@(THRESHOLD)</name> </threshold> </hudson.tasks.BuildTrigger>'

'postbuildtask': "<hudson.plugins.postbuildtask.PostbuildTask> <tasks> <hudson.plugins.postbuildtask.TaskProperties> <logTexts> <hudson.plugins.postbuildtask.LogProperties> <logText>Building remotely on</logText> <operator>AND</operator> </hudson.plugins.postbuildtask.LogProperties> </logTexts> <EscalateStatus>false</EscalateStatus> <RunIfJobSuccessful>false</RunIfJobSuccessful> <script>#!/bin/bash\nif [ -d $WORKSPACE/../aux ]; then\nsudo rm -rf $WORKSPACE/../aux\nfi</script> </hudson.plugins.postbuildtask.TaskProperties> </tasks> </hudson.plugins.postbuildtask.PostbuildTask>"

'pipelinetrigger': '<au.com.centrumsystems.hudson.plugin.buildpipeline.trigger.BuildPipelineTrigger> <downstreamProjectNames>@(PIPELINETRIGGER_PROJECT)</downstreamProjectNames> </au.com.centrumsystems.hudson.plugin.buildpipeline.trigger.BuildPipelineTrigger>'

'execute_shell': '<builders> <hudson.tasks.Shell> <command>@(COMMAND)</command> </hudson.tasks.Shell> </builders>'
